"""Initial migration with UUID

Revision ID: 7262e76ae6e5
Revises: 
Create Date: 2026-04-25 00:12:24.070053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7262e76ae6e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', name='actiontype'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('entry_reason', sa.String(), nullable=True),
    sa.Column('llm_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_pair'), 'decisions', ['pair'], unique=False)
    op.create_index(op.f('ix_decisions_timestamp'), 'decisions', ['timestamp'], unique=False)
    op.create_table('sentiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('source_type', sa.Enum('news', 'social', name='sourcetype'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiments_asset'), 'sentiments', ['asset'], unique=False)
    op.create_index(op.f('ix_sentiments_id'), 'sentiments', ['id'], unique=False)
    op.create_index(op.f('ix_sentiments_timestamp'), 'sentiments', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'CLOSED_PROFIT', 'CLOSED_LOSS', 'CANCELED', name='tradestatus'), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('actual_move', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('loss_reason_analysis', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_exchange_order_id'), 'trades', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_pair'), 'trades', ['pair'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_pair'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_exchange_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_sentiments_timestamp'), table_name='sentiments')
    op.drop_index(op.f('ix_sentiments_id'), table_name='sentiments')
    op.drop_index(op.f('ix_sentiments_asset'), table_name='sentiments')
    op.drop_table('sentiments')
    op.drop_index(op.f('ix_decisions_timestamp'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_pair'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
