trading:
  pairs:
    - BTCUSDT
    # - ETHUSDT
    # - SOLUSDT
    # - XRPUSDT
    # - HYPEUSDT
    # - ADAUSDT
    # - ARBUSDT
  correlation_pairs:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - XRPUSDT
    - HYPEUSDT
    - ADAUSDT
    - ARBUSDT
  active_session: "london_ny" # marker untuk logic session
